exclude: []
include: ['feed.xml']
encoding : utf-8
timezone: Asia/Shanghai
markdown: rdiscount
highlighter: pygments
paginate: 12
permalink: /:title
title: 莫离君的小博
description: 若问生涯原是梦，除梦里，没人知。
url: http://gongvirgil.github.io
feed: /feed.xml
author_info: <a href="http://gongvirgil.github.io/">GongVirgil</a>
short_name: gongvirgil
pre-site: gong-
param-cate: CATE
param-tag: TAG
