markdown: rdiscount
highlighter: pygments
paginate: 4
permalink: /blog/:year-:month-:day/:title.html
title: site of gongvirgil
url: http://gongvirgil.hithub.io
feed: /atom.xml
author_info: <a href="http://gongvirgil.hithub.io/">GongVirgil</a>
