auto: true
markdown: rdiscount
pygments: true
paginate: 8
permalink: /:title
title: site of gongvirgil
url: http://gongvirgil.hithub.io
feed: /atom.xml
author_info: <a href="http://gongvirgil.hithub.io/">GongVirgil</a>
