exclude: []
include: []
encoding : utf-8
timezone: Asia/Shanghai
markdown: rdiscount
highlighter: pygments
paginate: 8
permalink: /blog/:year-:month-:day/:title.html
title: site of gongvirgil
url: http://gongvirgil.github.io
feed: /atom.xml
author_info: <a href="http://gongvirgil.github.io/">GongVirgil</a>
short_name: gongvirgil
pre-site: gong-
pre-cate: 分类-
pre-tag: 标签-
